"""Made changes to address schema

Revision ID: e540182b734b
Revises: 
Create Date: 2023-07-12 14:20:59.816231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e540182b734b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Address', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'Location', ['location_id'], ['id'])
        batch_op.drop_column('city_id')
        batch_op.drop_column('country_id')
        batch_op.drop_column('state_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Address', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('country_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('city_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'State', ['state_id'], ['id'])
        batch_op.create_foreign_key(None, 'City', ['city_id'], ['id'])
        batch_op.create_foreign_key(None, 'Country', ['country_id'], ['id'])
        batch_op.drop_column('location_id')

    # ### end Alembic commands ###
